"""Add User model and update relationships

Revision ID: 0b21fb6a3651
Revises: 003
Create Date: 2026-01-12 07:03:08.986151

"""

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0b21fb6a3651"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "role", sa.String(length=50), nullable=False, comment="Role: user, admin, superadmin"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # Keep embedding as VECTOR type (don't convert to JSON)
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(op.f("ix_articles_law_id"), "articles", ["law_id"], unique=False)
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.drop_index(op.f("idx_conversations_id"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_session_id"), table_name="conversations")
    op.create_index("idx_conversations_session_id", "conversations", ["session_id"], unique=False)
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversations_session_id"), "conversations", ["session_id"], unique=True
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_foreign_key(None, "conversations", "users", ["user_id"], ["id"], ondelete="SET NULL")
    # Keep suggested_categories as ARRAY type (don't convert to JSON)
    op.drop_constraint(op.f("laws_reference_key"), "laws", type_="unique")
    op.create_index("idx_laws_reference", "laws", ["reference"], unique=False)
    op.create_index("idx_laws_status", "laws", ["status"], unique=False)
    op.create_index(op.f("ix_laws_category_id"), "laws", ["category_id"], unique=False)
    op.create_index(op.f("ix_laws_id"), "laws", ["id"], unique=False)
    op.create_index(op.f("ix_laws_language"), "laws", ["language"], unique=False)
    op.create_index(op.f("ix_laws_reference"), "laws", ["reference"], unique=True)
    op.create_index(op.f("ix_laws_status"), "laws", ["status"], unique=False)
    op.create_index(op.f("ix_message_feedback_id"), "message_feedback", ["id"], unique=False)
    op.drop_index(op.f("idx_messages_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_persona_interactions_conversation_id"),
        "persona_interactions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_interactions_id"), "persona_interactions", ["id"], unique=False
    )
    op.create_index(op.f("ix_persona_stats_id"), "persona_stats", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_persona_stats_id"), table_name="persona_stats")
    op.drop_index(op.f("ix_persona_interactions_id"), table_name="persona_interactions")
    op.drop_index(
        op.f("ix_persona_interactions_conversation_id"), table_name="persona_interactions"
    )
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.create_index(op.f("idx_messages_id"), "messages", ["id"], unique=False)
    op.drop_index(op.f("ix_message_feedback_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_laws_status"), table_name="laws")
    op.drop_index(op.f("ix_laws_reference"), table_name="laws")
    op.drop_index(op.f("ix_laws_language"), table_name="laws")
    op.drop_index(op.f("ix_laws_id"), table_name="laws")
    op.drop_index(op.f("ix_laws_category_id"), table_name="laws")
    op.drop_index("idx_laws_status", table_name="laws")
    op.drop_index("idx_laws_reference", table_name="laws")
    op.create_unique_constraint(
        op.f("laws_reference_key"), "laws", ["reference"], postgresql_nulls_not_distinct=False
    )
    # NOTE : upgrade() ne convertit deliberement PAS suggested_categories
    # (cf. ligne 58, "Keep suggested_categories as ARRAY type"). La conversion
    # inverse generee automatiquement ici echouait donc sur une vraie base.
    # upgrade() cree la FK sans nom (ligne 57) ; Postgres la nomme donc
    # deterministiquement conversations_user_id_fkey. drop_constraint(None, ...)
    # etait incompilable : "Can't emit DROP CONSTRAINT ... it has no name".
    op.drop_constraint(
        "conversations_user_id_fkey", "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_session_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_index("idx_conversations_session_id", table_name="conversations")
    op.create_index(
        op.f("idx_conversations_session_id"), "conversations", ["session_id"], unique=True
    )
    op.create_index(op.f("idx_conversations_id"), "conversations", ["id"], unique=False)
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_articles_law_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    # Idem pour articles.embedding : upgrade() le laisse en VECTOR (ligne 45),
    # et la dimension generee ici (768) ne correspondait meme pas au schema
    # reel (3072, cf. migration 7a8b9c0d1e2f).
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    # drop_table("users") etait appele DEUX fois : le second echouait toujours.
    op.drop_table("users")
    # ### end Alembic commands ###
