"""add_file_tracking_real

Revision ID: 3f0760423953
Revises: 006
Create Date: 2026-01-15 04:34:38.060616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_file_tracking_real

Revision ID: 3f0760423953
Revises: 006
Create Date: 2026-01-15 04:34:38.060616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0760423953'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('articles', 'embedding',
    #            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    op.add_column('laws', sa.Column('file_id', sa.String(length=100), nullable=True))
    op.add_column('laws', sa.Column('original_filename', sa.String(length=500), nullable=True))
    # op.alter_column('laws', 'suggested_categories',
    #            existing_type=postgresql.ARRAY(sa.INTEGER()),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    # op.drop_index(op.f('idx_laws_processing_progress'), table_name='laws')
    op.create_index(op.f('ix_laws_file_id'), 'laws', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laws_file_id'), table_name='laws')
    # op.create_index(op.f('idx_laws_processing_progress'), 'laws', ['processing_progress'], unique=False)
    # op.alter_column('laws', 'suggested_categories',
    #            existing_type=sa.JSON(),
    #            type_=postgresql.ARRAY(sa.INTEGER()),
    #            existing_nullable=True)
    op.drop_column('laws', 'original_filename')
    op.drop_column('laws', 'file_id')
    # op.alter_column('articles', 'embedding',
    #            existing_type=sa.JSON(),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
    #            existing_nullable=True)
    # ### end Alembic commands ###
