"""
Database models for RAG conversation tracking.

Stores conversation sessions and individual messages with sources and metadata.
"""

from datetime import date, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.core.database import Base


class Conversation(Base):
    """
    Conversation session tracking for RAG chatbot.

    Each conversation represents a session with a specific persona and language.
    Conversations can span multiple questions and maintain context.
    """

    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(100), unique=True, index=True, nullable=False)
    user_id = Column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    persona = Column(String(50), nullable=False)  # citoyen/avocat/entrepreneur/étudiant
    language = Column(String(2), nullable=False, default="fr")  # fr/en
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="conversations", lazy="selectin")
    messages = relationship(
        "Message",
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.created_at",
    )

    def __repr__(self):
        return f"<Conversation(id={self.id}, session_id={self.session_id}, persona={self.persona})>"


class Message(Base):
    """
    Individual messages in conversation (user questions and assistant responses).

    Stores message content, role, sources, confidence, and performance metrics.
    """

    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(
        Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role = Column(String(20), nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    sources = Column(JSON, nullable=True)  # [{"law_id": 1, "article_number": "5", ...}]
    confidence = Column(Float, nullable=True)  # 0.0-1.0 for assistant messages
    retrieval_time_ms = Column(Integer, nullable=True)
    generation_time_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")

    def __repr__(self):
        return f"<Message(id={self.id}, role={self.role}, conversation_id={self.conversation_id})>"


# Create indexes for performance
Index("idx_conversations_session_id", Conversation.session_id)
Index("idx_messages_conversation_id", Message.conversation_id)
Index("idx_messages_created_at", Message.created_at.desc())


class PersonaStat(Base):
    """
    Aggregated daily statistics per persona.

    Generated by Celery task daily at midnight UTC.
    Provides pre-aggregated metrics for fast analytics queries.
    """

    __tablename__ = "persona_stats"

    id = Column(Integer, primary_key=True, index=True)
    persona = Column(String(50), nullable=False)  # citoyen|avocat|entrepreneur|étudiant
    date = Column(Date, nullable=False)

    # Usage Metrics
    total_questions = Column(Integer, nullable=False, default=0)
    total_conversations = Column(Integer, nullable=False, default=0)
    unique_sessions = Column(Integer, nullable=False, default=0)

    # Performance Metrics
    avg_confidence = Column(Float, nullable=False, default=0.0)
    avg_retrieval_time_ms = Column(Integer, nullable=False, default=0)
    avg_generation_time_ms = Column(Integer, nullable=False, default=0)
    avg_total_time_ms = Column(Integer, nullable=False, default=0)

    # Engagement Metrics
    avg_messages_per_conversation = Column(Float, nullable=False, default=0.0)
    avg_session_duration_seconds = Column(Integer, nullable=False, default=0)

    # Quality Metrics
    helpful_count = Column(Integer, nullable=False, default=0)
    unhelpful_count = Column(Integer, nullable=False, default=0)
    satisfaction_rate = Column(Float, nullable=False, default=0.0)

    # Metadata
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (UniqueConstraint("persona", "date", name="uq_persona_date"),)

    def __repr__(self):
        return f"<PersonaStat(persona={self.persona}, date={self.date}, questions={self.total_questions})>"


class MessageFeedback(Base):
    """
    User ratings and feedback on assistant messages.

    Allows users to rate messages with 👍/👎 and optional rating (1-5).
    One feedback per message (unique constraint).
    """

    __tablename__ = "message_feedback"

    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(
        Integer, ForeignKey("messages.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    helpful = Column(Boolean, nullable=False)
    rating = Column(Integer, nullable=True)  # 1-5 scale
    comment = Column(Text, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Relationships
    message = relationship("Message", backref="feedback")

    __table_args__ = (CheckConstraint("rating >= 1 AND rating <= 5", name="ck_rating_range"),)

    def __repr__(self):
        return f"<MessageFeedback(message_id={self.message_id}, helpful={self.helpful})>"


class PersonaInteraction(Base):
    """
    Per-session analytics for persona usage.

    Tracks question/answer counts, confidence, response times, and persona switches
    within a conversation session.
    """

    __tablename__ = "persona_interactions"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(
        Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    persona = Column(String(50), nullable=False)
    language = Column(String(2), nullable=False)

    # Interaction Counts
    question_count = Column(Integer, nullable=False, default=0)
    answer_count = Column(Integer, nullable=False, default=0)

    # Performance
    avg_confidence = Column(Float, nullable=False, default=0.0)
    total_response_time_ms = Column(Integer, nullable=False, default=0)

    # Persona Behavior
    personas_used = Column(JSON, nullable=True)  # Array of all personas used
    persona_switches = Column(Integer, nullable=False, default=0)

    # Metadata
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    conversation = relationship("Conversation", backref="persona_interactions")

    def __repr__(self):
        return (
            f"<PersonaInteraction(conversation_id={self.conversation_id}, persona={self.persona})>"
        )


# Create indexes for analytics tables
Index("idx_persona_stats_persona_date", PersonaStat.persona, PersonaStat.date.desc())
Index("idx_persona_stats_date", PersonaStat.date.desc())
Index(
    "idx_message_feedback_message_id_helpful", MessageFeedback.message_id, MessageFeedback.helpful
)
Index("idx_message_feedback_created_at", MessageFeedback.created_at.desc())
Index("idx_message_feedback_helpful", MessageFeedback.helpful)
Index(
    "idx_persona_interactions_persona_created",
    PersonaInteraction.persona,
    PersonaInteraction.created_at.desc(),
)
Index("idx_persona_interactions_conversation_id", PersonaInteraction.conversation_id)
Index("idx_persona_interactions_created_at", PersonaInteraction.created_at.desc())
